### ISSUE TITLE
/tor/torrc.da: No such file or directory

### ISSUE THREAD

**Issue by pubkey** [antitree/private-tor-network#9] opened 2017-11-28 10:48 UTC
When I start the containers via docker-componse, I get the following error:
```bash
privatetornetwork_da3_1 exited with code 1
client_1  | cat: /tor/torrc.da: No such file or directory
privatetornetwork_client_1 exited with code 1
relay_1   | cat: /tor/torrc.da: No such file or directory
exit_1    | cat: /tor/torrc.da: No such file or directory
hs_1      | cat: /tor/torrc.da: No such file or directory
```

I think this is because of line [96](https://github.com/antitree/private-tor-network/blob/master/scripts/docker-entrypoint#L96) where it is using `cat ${TOR_DIR}/torrc.da >> /etc/tor/torrc` but according to the Dockerfile, `${TOR_DIR}` is resolved to `/tor` while every other config is in the folder `/etc/tor`

**Comment by antitree** [comment] 2017-11-28 13:06
Interesting. Looking into it

**Comment by pubkey** [comment] 2017-11-28 18:43
I'm using the docker-compose v2 btw.
```bash
docker-compose -f ./docker-compose.2.yml up
```

**docker-compose version 1.8.0, build unknown**

**Comment by antitree** [comment] 2018-04-25 20:22
This was caused by the way I was discovering the relay's IP addresses. It should be fixed now.

**Closed as completed by antitree** 2018-04-25 20:22 UTC

**Comment by mehulenc** [comment] 2024-03-11 15:29
> This was caused by the way I was discovering the relay's IP addresses. It should be fixed now.

Can you please let me know what change you did to fix this? I still am facing the same issue :(
